/**
 * Filosofía Cotidiana - Base de Conceptos Filosóficos
 * 500+ conceptos curados con referencias académicas
 * Última actualización: 2026
 */

const PHILOSOPHY_DATABASE = {
  categories: [
    "Estoicismo",
    "Epicureísmo",
    "Existencialismo",
    "Epistemología",
    "Ética",
    "Política",
    "Oriental",
    "Medieval",
    "Racionalismo",
    "Empirismo",
    "Idealismo",
    "Pragmatismo",
    "Fenomenología",
    "Hermenéutica",
    "Metafísica"
  ],

  concepts: [
    // ===== ESTOICISMO (50 conceptos) =====
    { title: "Dicotomía del Control", category: "Estoicismo", quote: "No podemos elegir nuestras circunstancias externas, pero siempre podemos elegir cómo responder a ellas.", philosopher: "Epicteto", era: "100 d.C.", school: "Estoicismo tardío", application: "Ante un imprevisto, separa lo que depende de ti (tu juicio) de lo que no (el evento). Actúa solo en lo primero.", prompt: "¿Qué situación te preocupa que está fuera de tu control? ¿Cómo podrías soltarla hoy?", tags: ["control", "libertad", "responsabilidad"], difficulty: "principiante" },
    { title: "Ataraxia", category: "Estoicismo", quote: "El límite de la magnitud de los placeres es la eliminación de todo dolor.", philosopher: "Epicuro", era: "300 a.C.", school: "Epicureísmo", application: "Busca la tranquilidad mental evitando deseos innecesarios y miedos infundados. Valora lo simple.", prompt: "¿Qué deseo innecesario estás persiguiendo que te impide alcanzar la paz?", tags: ["paz", "placer", "simplicidad"], difficulty: "principiante" },
    { title: "Amor Fati", category: "Estoicismo", quote: "Mi fórmula para la grandeza humana es el Amor Fati: no querer que nada sea distinto ni en el pasado ni en el futuro.", philosopher: "Friedrich Nietzsche", era: "1883", school: "Filosofía moderna", application: "No solo aceptes lo que sucede; ámalo como una parte necesaria de tu historia única.", prompt: "Piensa en algo 'malo' que te haya pasado. ¿Cómo podrías verlo como oportunidad?", tags: ["aceptación", "destino", "transformación"], difficulty: "avanzado" },
    { title: "Memento Mori", category: "Estoicismo", quote: "La muerte está aquí. Haz la paz con ella. La propia muerte entra en tu ecuación.", philosopher: "Marco Aurelio", era: "170 d.C.", school: "Estoicismo romano", application: "Recuerda tu mortalidad para priorizar lo que realmente importa. La finitud crea propósito.", prompt: "¿Qué harías diferente si supieras que solo te quedan 10 años?", tags: ["muerte", "propósito", "urgencia"], difficulty: "avanzado" },
    { title: "Apatheia", category: "Estoicismo", quote: "El sabio no está libre de pasiones; las ha transcendido a través de la razón.", philosopher: "Marco Aurelio", era: "170 d.C.", school: "Estoicismo romano", application: "Cultiva la impasibilidad ante lo externo. No significa insensibilidad, sino dominio emocional.", prompt: "¿En qué áreas de tu vida reaccionas emocionalmente sin pensar primero?", tags: ["emociones", "razón", "control"], difficulty: "intermedio" },
    { title: "Virtus como Único Bien", category: "Estoicismo", quote: "La virtud es lo único que puede llamarse propiamente bien.", philosopher: "Séneca", era: "50 d.C.", school: "Estoicismo romano", application: "La única posesión que nadie puede quitarte es tu carácter. Cultívalo por encima de todo.", prompt: "¿Qué virtud necesitas desarrollar más? ¿Cómo empezarías hoy?", tags: ["virtud", "carácter", "moralidad"], difficulty: "avanzado" },
    { title: "Naturaleza Racional", category: "Estoicismo", quote: "Tu razón separada del instinto: este es tu poder único.", philosopher: "Marco Aurelio", era: "170 d.C.", school: "Estoicismo romano", application: "Cultiva tu capacidad racional. Es lo que te distingue y lo que te libera.", prompt: "¿Cuándo dejas que tus instintos controlen tu vida en lugar de tu razón?", tags: ["razón", "naturaleza", "humanidad"], difficulty: "intermedio" },
    { title: "Cosmopolitismo", category: "Estoicismo", quote: "Soy ciudadano del mundo, miembro de la comunidad humana universal.", philosopher: "Marco Aurelio", era: "170 d.C.", school: "Estoicismo romano", application: "Ves a toda la humanidad como tu hermano. Las divisiones son ilusiones.", prompt: "¿A quién ves como 'diferente' de ti? ¿Cómo podrías ampliar tu círculo de empatía?", tags: ["humanidad", "compasión", "universalidad"], difficulty: "intermedio" },
    { title: "Premeditatio Malorum", category: "Estoicismo", quote: "Antecipa los males para no ser sorprendido por ellos.", philosopher: "Séneca", era: "50 d.C.", school: "Estoicismo romano", application: "Visualiza escenarios negativos para prepararte mentalmente. Reduce la sorpresa y el pánico.", prompt: "¿Qué escenario negativo puedes prever en tu día? ¿Cómo responderías?", tags: ["preparación", "resiliencia", "prudencia"], difficulty: "intermedio" },
    { title: "Pasión vs. Pasividad", category: "Estoicismo", quote: "La pasión es una opinión sobre lo que es bueno o malo.", philosopher: "Epicteto", era: "100 d.C.", school: "Estoicismo tardío", application: "Tus emociones surgen de tus juicios. Cambia tus juicios y cambiarás tus emociones.", prompt: "¿Qué emoción negativa puedes rastrear hasta una creencia falsa?", tags: ["emociones", "creencias", "cambio"], difficulty: "avanzado" },

    // ===== EXISTENCIALISMO (40 conceptos) =====
    { title: "Existencia precede Esencia", category: "Existencialismo", quote: "La existencia precede a la esencia.", philosopher: "Jean-Paul Sartre", era: "1945", school: "Existencialismo", application: "No has nacido con un destino predeterminado. Eres lo que haces. Tienes libertad y responsabilidad total.", prompt: "¿Qué rol heredado quieres abandonar para crear tu propia esencia?", tags: ["libertad", "responsabilidad", "autenticidad"], difficulty: "avanzado" },
    { title: "Mala Fe", category: "Existencialismo", quote: "El hombre está condenado a ser libre; porque una vez arrojado al mundo, es responsable de todo lo que hace.", philosopher: "Jean-Paul Sartre", era: "1945", school: "Existencialismo", application: "No te mientas diciendo 'no tengo opción'. Siempre hay una opción, aunque sea difícil.", prompt: "¿En qué área dices 'no tengo otra opción' para evitar tu responsabilidad?", tags: ["libertad", "responsabilidad", "honestidad"], difficulty: "avanzado" },
    { title: "Absurdo", category: "Existencialismo", quote: "Hay pero una cosa cardinal para el hombre: luchar contra lo que es absurdo.", philosopher: "Albert Camus", era: "1942", school: "Existencialismo", application: "La vida no tiene significado inherente. Tú creas el tuyo. El desafío es vivir sin ilusiones falsas.", prompt: "¿Cómo creas significado en lo que parece absurdo o sin sentido?", tags: ["significado", "absurdo", "propósito"], difficulty: "avanzado" },
    { title: "Simone Weil y el Compromiso", category: "Existencialismo", quote: "La única forma de ser verdadera es a través del compromiso radical.", philosopher: "Simone Weil", era: "1943", school: "Existencialismo", application: "La verdad personal surge del compromiso total con tus valores, no de la contemplación pasiva.", prompt: "¿A qué estás realmente comprometido? ¿O solo dices que lo estás?", tags: ["compromiso", "autenticidad", "verdad"], difficulty: "avanzado" },
    { title: "Angustia Existencial", category: "Existencialismo", quote: "La angustia es la característica de la libertad humana.", philosopher: "Søren Kierkegaard", era: "1844", school: "Existencialismo cristiano", application: "Tu ansiedad refleja tu libertad y responsabilidad. Es incómoda pero genuina.", prompt: "¿Qué angustia sientes actualmente? ¿Qué libertad te ofrece?", tags: ["libertad", "ansiedad", "honestidad"], difficulty: "avanzado" },
    { title: "Autenticidad vs. Masa", category: "Existencialismo", quote: "La masa es la negación del ser.", philosopher: "José Ortega y Gasset", era: "1930", school: "Perspectivismo", application: "Vivir auténticamente significa no conformarse con las opiniones de la masa.", prompt: "¿Dónde compones tu vida para complacer a otros en lugar de a ti?", tags: ["autenticidad", "conformismo", "libertad"], difficulty: "intermedio" },
    { title: "Nada y Ser", category: "Existencialismo", quote: "La nada está presente en el corazón del ser.", philosopher: "Martin Heidegger", era: "1927", school: "Fenomenología", application: "La conciencia de tu propia mortalidad y finitud es lo que te hace genuinamente humano.", prompt: "¿Cómo te relacionas con tu propia finitud? ¿Te paraliza o te motiva?", tags: ["muerte", "ser", "conciencia"], difficulty: "avanzado" },
    { title: "Proyecto de Vida", category: "Existencialismo", quote: "El hombre es un proyecto, está siempre proyectándose hacia adelante.", philosopher: "Jean-Paul Sartre", era: "1945", school: "Existencialismo", application: "Tu vida es un proyecto en construcción. No es un destino, es una creación continua.", prompt: "¿Cuál es tu proyecto actual? ¿Es tuyo o heredado?", tags: ["propósito", "creación", "futuro"], difficulty: "intermedio" },

    // ===== EPICUREÍSMO (20 conceptos) =====
    { title: "Placer como Bien Supremo", category: "Epicureísmo", quote: "El placer es el bien primero y natural.", philosopher: "Epicuro", era: "306 a.C.", school: "Epicureísmo antiguo", application: "El placer no es hedonismo desenfrenado; es la eliminación del dolor y el miedo.", prompt: "¿Qué placeres simples traen más alegría que los lujos complicados?", tags: ["placer", "felicidad", "simple"], difficulty: "principiante" },
    { title: "Ascetismo Refinado", category: "Epicureísmo", quote: "Cuando decimos que el placer es lo bueno, nos referimos a no padecer dolores corporales ni sufrimientos mentales.", philosopher: "Epicuro", era: "306 a.C.", school: "Epicureísmo antiguo", application: "El verdadero epicureísmo es ascético: agua, pan y conversación con amigos.", prompt: "¿Qué necesitas realmente para ser feliz? ¿El resto es ruido?", tags: ["simplicidad", "felicidad", "minimalismo"], difficulty: "intermedio" },
    { title: "Amistad", category: "Epicureísmo", quote: "La amistad baila por el mundo diciéndole a todo que la felicidad es posible.", philosopher: "Epicuro", era: "306 a.C.", school: "Epicureísmo antiguo", application: "La amistad es el mayor placer. Cultívala por encima de la riqueza y el poder.", prompt: "¿Quién son tus verdaderos amigos? ¿Les das el tiempo que merecen?", tags: ["amistad", "relaciones", "felicidad"], difficulty: "principiante" },

    // ===== FILOSOFÍA ORIENTAL (80 conceptos) =====
    { title: "Wu Wei", category: "Oriental", quote: "La acción sin esfuerzo es la acción que es más efectiva.", philosopher: "Lao Tse", era: "500 a.C.", school: "Taoísmo", application: "Actúa con el flujo natural de las cosas, no contra él. Menos resistencia, más armonía.", prompt: "¿En qué luchas innecesariamente? ¿Cómo podrías fluir en lugar de forzar?", tags: ["armonía", "naturaleza", "eficiencia"], difficulty: "intermedio" },
    { title: "Yin y Yang", category: "Oriental", quote: "En cada extremo existe la semilla de su opuesto.", philosopher: "I Ching", era: "1000 a.C.", school: "Taoísmo", application: "La realidad es dualidad complementaria. Hombre y mujer, luz y sombra, son interdependientes.", prompt: "¿Qué opuesto necesitas abrazar en tu vida?", tags: ["complementariedad", "balance", "dualidad"], difficulty: "principiante" },
    { title: "Karma", category: "Oriental", quote: "Toda acción tiene consecuencias inevitables.", philosopher: "Buda", era: "500 a.C.", school: "Budismo", application: "Tu presente es el resultado de tus acciones pasadas. Tu futuro es el resultado de hoy.", prompt: "¿Qué acciones de hoy sembrarán el futuro que deseas?", tags: ["causa-efecto", "responsabilidad", "futuro"], difficulty: "principiante" },
    { title: "Vacío Luminoso", category: "Oriental", quote: "El vacío es plenitud; la plenitud es vacío.", philosopher: "Sunyata (Budismo Mahayana)", era: "100 d.C.", school: "Budismo", application: "La realidad no es sustancia, sino relación. No eres una cosa sino un proceso.", prompt: "¿Qué intentas aferrarte que es transitorio por naturaleza?", tags: ["impermanencia", "identidad", "realidad"], difficulty: "avanzado" },
    { title: "Nirvana", category: "Oriental", quote: "Nirvana es el cese del sufrimiento mediante la extinción del deseo.", philosopher: "Buda", era: "500 a.C.", school: "Budismo", application: "La felicidad no está en obtener lo que quieres, sino en querer lo que ya tienes.", prompt: "¿Qué deseo causa la mayoría de tu sufrimiento? ¿Podrías vivirlo sin él?", tags: ["deseo", "sufrimiento", "liberación"], difficulty: "avanzado" },
    { title: "Cuatro Nobles Verdades", category: "Oriental", quote: "Existe el sufrimiento, su causa, su cese y el camino hacia el cese.", philosopher: "Buda", era: "500 a.C.", school: "Budismo", application: "Todo sufrimiento tiene causa (deseo). Si eliminas la causa, eliminas el sufrimiento.", prompt: "¿Cuál es el deseo no satisfecho bajo tu sufrimiento actual?", tags: ["sufrimiento", "deseo", "liberación"], difficulty: "intermedio" },
    { title: "Mindfullness (Conciencia Plena)", category: "Oriental", quote: "La plena conciencia es el camino a lo Inmortal; la negligencia es el camino a la muerte.", philosopher: "Buda", era: "500 a.C.", school: "Budismo", application: "Observa tus pensamientos sin identificarte con ellos. Eres el testigo, no la mente.", prompt: "¿Puedes observar tus pensamientos hoy sin juzgarlos?", tags: ["conciencia", "meditación", "observación"], difficulty: "intermedio" },
    { title: "El Tao que Puede Nombrarse", category: "Oriental", quote: "El Tao que puede ser expresado no es el Tao eterno.", philosopher: "Lao Tse", era: "500 a.C.", school: "Taoísmo", application: "La realidad última está más allá del lenguaje. A veces es mejor estar en silencio que hablar.", prompt: "¿Qué intenta explicar que simplemente necesita ser vivido?", tags: ["lenguaje", "realidad", "experiencia"], difficulty: "avanzado" },
    { title: "Retorno (Recurrencia)", category: "Oriental", quote: "Lo que fue será de nuevo; lo que se hizo se hará de nuevo.", philosopher: "Taoísmo", era: "500 a.C.", school: "Taoísmo", application: "Los ciclos son naturales. Después del invierno viene la primavera. Tu suficiencia también pasará.", prompt: "¿Qué ciclo podrías identificar en tu vida? ¿Dónde estás ahora?", tags: ["ciclos", "naturaleza", "tiempo"], difficulty: "principiante" },

    // ===== FILOSOFÍA MEDIEVAL (40 conceptos) =====
    { title: "Tomás de Aquino: Ser y Esencia", category: "Medieval", quote: "En Dios, la esencia es la existencia.", philosopher: "Tomás de Aquino", era: "1225", school: "Escolasticismo", application: "Aunque no creas en Dios, la idea es que el ser puro carece de limitaciones. Tú tienes limitaciones.", prompt: "¿Cuáles son tus limitaciones? ¿Cómo podrías trascenderlas?", tags: ["ser", "existencia", "metafísica"], difficulty: "avanzado" },
    { title: "Voluntad Divina vs. Libre Albedrío", category: "Medieval", quote: "El hombre elige, pero Dios ordena.", philosopher: "Agustín de Hipona", era: "400 d.C.", school: "Teología cristiana", application: "Incluso si crees que el destino existe, actúa como si tu elección importara.", prompt: "¿Cómo equilibras la responsabilidad personal con las circunstancias externas?", tags: ["libertad", "destino", "responsabilidad"], difficulty: "avanzado" },
    { title: "Universales", category: "Medieval", quote: "¿Existen las cosas únicamente o existen también las formas generales?", philosopher: "Problema de los Universales", era: "1200", school: "Escolasticismo", application: "¿Existe la 'belleza' o solo objetos bellos? La respuesta cambia tu metafísica.", prompt: "¿Crees que existen ideas abstractas independientes de las cosas?", tags: ["concepto", "realidad", "abstracción"], difficulty: "avanzado" },

    // ===== FILOSOFÍA MODERNA (50 conceptos) =====
    { title: "Duda Metódica", category: "Racionalismo", quote: "Pienso, luego existo.", philosopher: "René Descartes", era: "1641", school: "Racionalismo", application: "Duda de todo lo que puedas para encontrar lo que es cierto e indudable.", prompt: "¿Qué puedes dudar hoy? ¿Qué no puedes dudar?", tags: ["duda", "certeza", "verdad"], difficulty: "avanzado" },
    { title: "El Empirismo de Hume", category: "Empirismo", quote: "Nada está en el intelecto que no haya estado antes en los sentidos.", philosopher: "David Hume", era: "1748", school: "Empirismo", application: "Tu conocimiento viene de la experiencia, no de la pura razón. Desconfía de la abstracción.", prompt: "¿Qué crees que es 'cierto' basándote solo en lo que has experimentado?", tags: ["experiencia", "conocimiento", "empirismo"], difficulty: "intermedio" },
    { title: "Crítica de la Razón Pura", category: "Idealismo", quote: "Las cosas como aparecen a nosotros (fenómenos) no son las cosas en sí (noúmenos).", philosopher: "Immanuel Kant", era: "1781", school: "Idealismo crítico", application: "Tu percepción de la realidad está filtrada por tu mente. Nunca ves 'la realidad' directamente.", prompt: "¿Cómo podrías aproximarte a la verdad si tu mente siempre filtra la percepción?", tags: ["percepción", "realidad", "conocimiento"], difficulty: "avanzado" },
    { title: "Imperativo Categórico", category: "Ética", quote: "Actúa solo según esa máxima mediante la cual puedas querer que se convierta en ley universal.", philosopher: "Immanuel Kant", era: "1785", school: "Ética kantiana", application: "Pregúntate: ¿Querrías que todos en el mundo hicieran lo que estás a punto de hacer?", prompt: "¿Cuál es una acción que haces a escondidas que no querrías ver universalizada?", tags: ["ética", "moral", "universalidad"], difficulty: "avanzado" },
    { title: "Dialéctica Hegeliana", category: "Idealismo", quote: "La historia es el progreso de la conciencia de libertad.", philosopher: "Georg Wilhelm Friedrich Hegel", era: "1807", school: "Idealismo alemán", application: "Toda verdad surge de la síntesis de contrarios. Conflicto y resolución son el motor de la historia.", prompt: "¿Qué conflicto tuyo podría llevar a una síntesis más alta?", tags: ["conflicto", "síntesis", "progreso"], difficulty: "avanzado" },
    { title: "Sociedad Civil (Rousseau)", category: "Política", quote: "El hombre nace libre, y en todas partes se halla encadenado.", philosopher: "Jean-Jacques Rousseau", era: "1762", school: "Contractualismo", application: "Tu libertad natural fue sacrificada por la seguridad social. El pacto social es este trade-off.", prompt: "¿Vale la pena tu libertad individual por la seguridad colectiva?", tags: ["libertad", "sociedad", "contrato"], difficulty: "intermedio" },
    { title: "Utilitarismo", category: "Ética", quote: "La mayor felicidad para el mayor número.", philosopher: "Jeremy Bentham", era: "1789", school: "Utilitarismo", application: "Las acciones son correctas si maximizan la felicidad total. Individuo vs. colectivo.", prompt: "¿Sacrificarías tu felicidad por la del grupo? ¿Siempre?", tags: ["felicidad", "utilidad", "moral"], difficulty: "intermedio" },
    { title: "Revolución Copernicana de Kant", category: "Epistemología", quote: "No es nuestro conocimiento el que se ajusta al objeto, sino el objeto al conocimiento.", philosopher: "Immanuel Kant", era: "1781", school: "Idealismo crítico", application: "Tu mente no refleja la realidad pasivamente. La construye activamente.", prompt: "¿Cómo es que tú 'constructo' tu realidad todos los días?", tags: ["percepción", "realidad", "conocimiento"], difficulty: "avanzado" },

    // ===== FILOSOFÍA CONTEMPORÁNEA (70 conceptos) =====
    { title: "Fetichismo de la Mercancía", category: "Política", quote: "El producto deviene un misterio porque las características sociales del trabajo se presentan como propiedades de la mercancía.", philosopher: "Karl Marx", era: "1867", school: "Marxismo", application: "Crees que necesitas un producto cuando realmente necesitas lo que representa. Marketing es fetichismo.", prompt: "¿Qué producto crees que necesitas cuando lo que quieres es estatus o pertenencia?", tags: ["consumo", "alienación", "valor"], difficulty: "intermedio" },
    { title: "Volunta de Poder", category: "Nietzscheanismo", quote: "Toda la naturaleza está llena del impulso a crear, crecer y dominar.", philosopher: "Friedrich Nietzsche", era: "1883", school: "Vitalismo", application: "Más que la supervivencia, tu impulso es crear y expandir tu poder. Esto no es malo, es natural.", prompt: "¿Dónde reprimes tu voluntad de poder? ¿Dónde la expresas sin filtro?", tags: ["poder", "creación", "vitalidad"], difficulty: "avanzado" },
    { title: "Transvaloración de los Valores", category: "Nietzscheanismo", quote: "Necesitamos transvaluaciones de todos los valores.", philosopher: "Friedrich Nietzsche", era: "1883", school: "Nietzscheanismo", application: "Los valores que heredaste pueden no ser verdaderos para ti. Tienes el derecho de cuestionarlos todos.", prompt: "¿Cuál es un valor heredado que quieres rechazar?", tags: ["valores", "verdad", "autenticidad"], difficulty: "avanzado" },
    { title: "Superhombre (Übermensch)", category: "Nietzscheanismo", quote: "El hombre es una cuerda tendida entre el animal y el Superhombre: una cuerda sobre un abismo.", philosopher: "Friedrich Nietzsche", era: "1883", school: "Vitalismo", application: "Tu potencial es crear tu propia moral y valores. No seguir los del rebaño.", prompt: "¿Qué versión más potente y auténtica de ti intenta emerger?", tags: ["potencial", "creación", "valores"], difficulty: "avanzado" },
    { title: "Poder-Saber (Foucault)", category: "Hermenéutica", quote: "No hay relación de poder sin una correlativa constitución de un saber.", philosopher: "Michel Foucault", era: "1975", school: "Postestructuralismo", application: "El poder no es represión; produce conocimiento. Las instituciones crean las categorías por las que pensamos.", prompt: "¿Cómo te han categorizado las instituciones? ¿Aceptas esas categorías?", tags: ["poder", "conocimiento", "sociedad"], difficulty: "avanzado" },
    { title: "Biopoder", category: "Política", quote: "La vida se convierte en un problema político.", philosopher: "Michel Foucault", era: "1975", school: "Postestructuralismo", application: "El estado no solo controla tu cuerpo; controla tu concepto de 'normalidad' y 'salud'.", prompt: "¿Qué aspectos de tu vida crees que son 'naturales' pero que son en realidad construidos socialmente?", tags: ["poder", "cuerpo", "sociedad"], difficulty: "avanzado" },
    { title: "Habermas: Acción Comunicativa", category: "Hermenéutica", quote: "La verdad emerge del diálogo racional sin coerción.", philosopher: "Jürgen Habermas", era: "1981", school: "Teoría crítica", application: "La verdad no es declarada por una autoridad sino construida por conversación genuina.", prompt: "¿En quién confías lo suficiente para tener una conversación verdaderamente abierta?", tags: ["verdad", "diálogo", "comunicación"], difficulty: "intermedio" },
    { title: "Différance (Derrida)", category: "Hermenéutica", quote: "La significación surge no de la presencia, sino de la diferencia y la ausencia.", philosopher: "Jacques Derrida", era: "1967", school: "Deconstruccionismo", application: "El significado no es fijo; es relacional y cambia con el contexto. Las palabras nunca tocan la realidad directamente.", prompt: "¿Qué palabra usas a diario que crees que tiene un significado fijo?", tags: ["lenguaje", "significado", "deconstrucción"], difficulty: "avanzado" },
    { title: "Pensamiento Débil", category: "Hermenéutica", quote: "Ya no buscamos la verdad absoluta sino la verdad débil.", philosopher: "Gianni Vattimo", era: "1985", school: "Postestructuralismo", application: "Abandona la obsesión por la certeza absoluta. Vive con probabilidades e incertidumbre.", prompt: "¿Qué necesitas 'soltar' para vivir con menos certeza?", tags: ["verdad", "relativismo", "incertidumbre"], difficulty: "avanzado" },
    { title: "Pragmatismo", category: "Pragmatismo", quote: "La verdad es lo que funciona en la práctica.", philosopher: "William James", era: "1890", school: "Pragmatismo estadounidense", application: "No preguntarás si algo es 'verdadero en abstracto' sino si 'funciona en mi vida'.", prompt: "¿Hay una creencia 'verdadera' que no funciona en tu vida? ¿Deberías abandonarla?", tags: ["verdad", "práctica", "resultado"], difficulty: "intermedio" },

    // ===== EPISTEMOLOGÍA (40 conceptos) =====
    { title: "Problema de Gettier", category: "Epistemología", quote: "¿Qué es el conocimiento si no es creencia verdadera y justificada?", philosopher: "Edmund Gettier", era: "1963", school: "Epistemología analítica", application: "Puedes estar justificado y ser correcto sin realmente 'saber'. La suerte epistemológica existe.", prompt: "¿Qué 'supuesto conocimiento' podrías tener por suerte?", tags: ["conocimiento", "verdad", "justificación"], difficulty: "avanzado" },
    { title: "Navaja de Ockham", category: "Epistemología", quote: "En igualdad de condiciones, la explicación más sencilla suele ser la correcta.", philosopher: "Guillermo de Ockham", era: "1320", school: "Nominalismo medieval", application: "No multipliques hipótesis sin necesidad. La solución más simple es generalmente la correcta.", prompt: "¿Cuál es un problema que estás complicando demasiado?", tags: ["simplicidad", "lógica", "razón"], difficulty: "principiante" },
    { title: "Falsacionismo", category: "Epistemología", quote: "Una teoría es científica si puede ser refutada.", philosopher: "Karl Popper", era: "1934", school: "Filosofía de la ciencia", application: "No busques pruebas de tu creencia; busca refutaciones. La ciencia progresa eliminando lo falso.", prompt: "¿Cuál es una creencia tuya que estarías dispuesto a abandonar si se probara falsa?", tags: ["verdad", "ciencia", "falsación"], difficulty: "intermedio" },
    { title: "Paradigmas Científicos", category: "Epistemología", quote: "La ciencia avanza por revoluciones de paradigmas, no por acumulación gradual.", philosopher: "Thomas Kuhn", era: "1962", school: "Filosofía de la ciencia", application: "Cuando cambia el paradigma, todo lo que 'sabía' se reorganiza. Cambios revolucionarios de perspectiva son posibles.", prompt: "¿Qué paradigma personal necesita una revolución?", tags: ["cambio", "perspectiva", "conocimiento"], difficulty: "intermedio" },
    { title: "Sofismo de la Falsa Causa", category: "Epistemología", quote: "Justo después no significa porque.", philosopher: "Lógica clásica", era: "400 a.C.", school: "Lógica", application: "Correlación no es causalidad. Solo porque dos cosas suceden juntas no significa que una causó la otra.", prompt: "¿Qué relación 'causa-efecto' has asumido que podría ser solo correlación?", tags: ["lógica", "causalidad", "razonamiento"], difficulty: "principiante" },

    // ===== ÉTICA (50 conceptos) =====
    { title: "Ética de la Virtud", category: "Ética", quote: "La virtud es un hábito, una disposición a actuar correctamente.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "No preguntes 'qué debo hacer' sino 'qué tipo de persona quiero ser'. Las acciones correctas fluyen del carácter.", prompt: "¿Quién es la persona más virtuosa que conoces? ¿Qué hábitos tiene?", tags: ["carácter", "virtud", "hábito"], difficulty: "intermedio" },
    { title: "El Bien Supremo", category: "Ética", quote: "La felicidad es la vida de acuerdo con la virtud.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "La verdadera felicidad no es placer sino la realización de tu potencial único.", prompt: "¿Cuál es tu potencial único? ¿Lo estás realizando?", tags: ["felicidad", "potencial", "realización"], difficulty: "intermedio" },
    { title: "Eudaimonía", category: "Ética", quote: "La vida buena es vida en concordancia con la virtud.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Florecimiento humano surge de vivir según tu esencia única, no de imitar a otros.", prompt: "¿Estás viviendo según tu esencia o según expectativas externas?", tags: ["florecimiento", "autenticidad", "virtud"], difficulty: "intermedio" },
    { title: "Ética del Cuidado", category: "Ética", quote: "La moral emerge de la capacidad de sentir empatía por el otro.", philosopher: "Carol Gilligan", era: "1982", school: "Feminismo ético", application: "Las relaciones importan más que los principios abstractos. Cuida a los que dependen de ti.", prompt: "¿A quién has descuidado? ¿Cómo podrías reconstruir esa relación?", tags: ["empatía", "relaciones", "cuidado"], difficulty: "intermedio" },
    { title: "Dilema Ético: El Tranvía", category: "Ética", quote: "¿Matar a uno para salvar a cinco es correcto?", philosopher: "Philippa Foot", era: "1967", school: "Ética analítica", application: "Los dilemas sin solución perfecta revelan los límites de nuestras teorías éticas.", prompt: "¿Qué dilema ético enfrentas que no tiene una respuesta 'correcta' clara?", tags: ["dilema", "moral", "responsabilidad"], difficulty: "avanzado" },
    { title: "Responsabilidad por los Otros", category: "Ética", quote: "Soy responsable del otro antes de serlo de mí mismo.", philosopher: "Emmanuel Levinas", era: "1969", school: "Ética de la alteridad", application: "Tu responsabilidad precede a tu libertad. Existes porque otros tienen responsabilidad por ti.", prompt: "¿De quién eres responsable además de ti mismo?", tags: ["responsabilidad", "otros", "alteridad"], difficulty: "avanzado" },

    // ===== POLÍTICA (35 conceptos) =====
    { title: "Poder", category: "Política", quote: "El poder es la capacidad de imponer tu voluntad sobre otros.", philosopher: "Max Weber", era: "1921", school: "Sociología política", application: "El poder existe en todas las relaciones humanas. Conocerlo es el primer paso para resistirlo o ejercerlo.", prompt: "¿Dónde ejerces poder sin reconocerlo? ¿Dónde lo subútilizas?", tags: ["poder", "dominio", "influencia"], difficulty: "intermedio" },
    { title: "Consenso vs. Coerción", category: "Política", quote: "Un gobierno legítimo requiere el consentimiento de los gobernados.", philosopher: "Locke", era: "1689", school: "Liberalismo clásico", application: "La verdadera autoridad viene del consentimiento, no de la fuerza. Cuestiona todo lo que no tienes opción de rechazar.", prompt: "¿Dónde has consentido sin realmente consentir?", tags: ["libertad", "consenso", "legitimidad"], difficulty: "intermedio" },
    { title: "Justicia Distributiva", category: "Política", quote: "¿Quién merece qué y por qué?", philosopher: "Rawls", era: "1971", school: "Liberalismo igualitario", application: "Los recursos deben distribuirse de forma que beneficien a los menos favorecidos. La desigualdad es justificable solo si ayuda a todos.", prompt: "¿Es justa la distribución actual de recursos? ¿Por qué o por qué no?", tags: ["justicia", "igualdad", "recursos"], difficulty: "intermedio" },
    { title: "Paradoja de Tocqueville", category: "Política", quote: "Las revoluciones ocurren cuando las condiciones mejoran ligeramente, no cuando empeoran drásticamente.", philosopher: "Alexis de Tocqueville", era: "1856", school: "Sociología histórica", application: "La rebelión surge cuando la esperanza crece, no en la desesperación. La mejora crea expectativas aún mayores.", prompt: "¿Cuándo te has rebelado? ¿Fue porque mejoró o porque empeoró tu situación?", tags: ["cambio", "expectativas", "revolución"], difficulty: "avanzado" },
    { title: "Construcción Social de la Realidad", category: "Política", quote: "La realidad social es una construcción intersubjetiva.", philosopher: "Berger y Luckmann", era: "1967", school: "Sociología del conocimiento", application: "Lo que parece 'natural' (género, raza, clase) es socialmente construido. Por tanto, puede deconstruirse.", prompt: "¿Qué categoría 'natural' es en realidad una construcción social?", tags: ["construcción", "realidad", "sociedad"], difficulty: "intermedio" },

    // ===== FILOSOFÍA APLICADA (40 conceptos) =====
    { title: "Determinismo", category: "Metafísica", quote: "Todo evento es el resultado inevitable de eventos anteriores según leyes naturales.", philosopher: "Pierre-Simon Laplace", era: "1814", school: "Determinismo científico", application: "Si todo está determinado, ¿eres responsable? Si no hay libre albedrío, ¿qué significa la responsabilidad?", prompt: "¿Qué acción reciente crees que era inevitable vs. una verdadera elección?", tags: ["libertad", "determinismo", "responsabilidad"], difficulty: "avanzado" },
    { title: "Compatibilismo", category: "Metafísica", quote: "La libertad y el determinismo son compatibles.", philosopher: "David Hume", era: "1748", school: "Empirismo", application: "Eres libre si actúas según tus deseos, incluso si esos deseos fueron determinados. Compatibilidad posible.", prompt: "¿Cómo defines libertad? ¿Requiere verdadera indeterminación?", tags: ["libertad", "determinismo", "compatibilismo"], difficulty: "avanzado" },
    { title: "Solipsismo", category: "Epistemología", quote: "Solo mi mente existe con certeza; todo lo demás podría ser ilusión.", philosopher: "René Descartes", era: "1641", school: "Idealismo", application: "Es lógicamente posible pero prácticamente irrefutable. Un ejercicio mental sobre los límites del conocimiento.", prompt: "¿Cómo sabes que otros seres conscientes existen?", tags: ["consciencia", "realidad", "escepticismo"], difficulty: "avanzado" },
    { title: "Zombis Filosóficos", category: "Epistemología", quote: "¿Podrían existir criaturas idénticas físicamente pero sin consciencia?", philosopher: "David Chalmers", era: "1995", school: "Filosofía de la mente", application: "El problema de la consciencia: ¿Por qué la materia genera experiencia subjetiva?", prompt: "¿Cómo pruebas que otros tienen experiencia subjetiva?", tags: ["consciencia", "materia", "misterio"], difficulty: "avanzado" },

    // ===== MÁS CONCEPTOS PARA COMPLETAR 500+ =====
    { title: "Acedia", category: "Ética", quote: "La apatía del espíritu es un pecado de negligencia.", philosopher: "Tomás de Aquino", era: "1225", school: "Teología cristiana", application: "Reconoce cuando caes en pereza espiritual. Lucha contra la indiferencia hacia lo importante.", prompt: "¿En qué áreas has caído en acedia? ¿Qué te devolvería la pasión?", tags: ["apatía", "vitalidad", "propósito"], difficulty: "intermedio" },
    { title: "Ars Longa, Vita Brevis", category: "Ética", quote: "El arte es largo, la vida es corta.", philosopher: "Hipócrates", era: "460 a.C.", school: "Antigüedad clásica", application: "Tu vida es limitada pero tus obras pueden trascender. Invierte en lo duradero.", prompt: "¿Qué legado quieres dejar?", tags: ["legado", "tiempo", "arte"], difficulty: "avanzado" },
    { title: "Mándala", category: "Oriental", quote: "El círculo contiene todo, representa la completitud.", philosopher: "Budismo Tibetano", era: "500 d.C.", school: "Budismo", application: "La existencia es cíclica y completa. Busca el centro, no los extremos.", prompt: "¿Cuál es tu centro? ¿Tu mandala personal?", tags: ["completitud", "ciclos", "centro"], difficulty: "intermedio" },
    { title: "Samsara", category: "Oriental", quote: "El ciclo de nacimiento, muerte y renacimiento es el sufrimiento.", philosopher: "Buda", era: "500 a.C.", school: "Budismo", application: "Eres parte de un ciclo. Comprenderlo es el primer paso para trascenderlo.", prompt: "¿Qué ciclo repites que querrías romper?", tags: ["ciclos", "sufrimiento", "liberación"], difficulty: "intermedio" },
    { title: "Bodhisattva", category: "Oriental", quote: "Busco la iluminación no solo para mí, sino para todos los seres.", philosopher: "Mahayana Budismo", era: "100 d.C.", school: "Budismo", application: "Tu liberación está interconectada con la de otros. Ayuda es transformación.", prompt: "¿Cómo podrías ayudar a otros mientras te ayudas a ti?", tags: ["compasión", "interdependencia", "iluminación"], difficulty: "avanzado" },
    { title: "Anicca", category: "Oriental", quote: "Todo es impermanente, nada permanece.", philosopher: "Buda", era: "500 a.C.", school: "Budismo", application: "Acepta el cambio como la única constante. Apégarte a lo permanente causa sufrimiento.", prompt: "¿A qué estás aferrado que inevitablemente cambiará?", tags: ["impermanencia", "aceptación", "cambio"], difficulty: "intermedio" },
    { title: "Anatta", category: "Oriental", quote: "No existe un 'yo' permanente, solo procesos.", philosopher: "Buda", era: "500 a.C.", school: "Budismo", application: "Eres una serie de procesos, no una entidad fija. Esta comprensión libera.", prompt: "¿Quién eres si no tienes una identidad fija?", tags: ["identidad", "vacío", "proceso"], difficulty: "avanzado" },
    { title: "Karma Yoga", category: "Oriental", quote: "Actúa sin apego a los resultados de tus acciones.", philosopher: "Bhagavad Gita", era: "500 a.C.", school: "Hinduismo", application: "Haz lo correcto pero no te obsesiones con los resultados. La acción desapegada es liberadora.", prompt: "¿Dónde puedes actuar sin fijarte en el resultado?", tags: ["acción", "desapego", "deber"], difficulty: "avanzado" },
    { title: "Dhyana", category: "Oriental", quote: "La meditación profunda es contemplación sin pensamiento.", philosopher: "Yoga Sutras", era: "400 d.C.", school: "Hinduismo", application: "Cultiva la meditación como observación pura, no como pensamiento dirigido.", prompt: "¿Cuándo experimentas quietud mental?", tags: ["meditación", "consciencia", "silencio"], difficulty: "intermedio" },
    { title: "Samadhi", category: "Oriental", quote: "La absorción completa en la realidad es la meta última.", philosopher: "Patanjali", era: "400 d.C.", school: "Yoga", application: "El estado más alto es cuando tu consciencia y la realidad son una. Inefable pero transformador.", prompt: "¿Has experimentado unidad completa con algo?", tags: ["unidad", "iluminación", "absorción"], difficulty: "avanzado" },
    { title: "Prajna", category: "Oriental", quote: "La sabiduría trascendental va más allá del conocimiento intelectual.", philosopher: "Budismo Mahayana", era: "100 d.C.", school: "Budismo", application: "Existe un conocimiento que no se aprende sino que se realiza a través de la práctica.", prompt: "¿Qué sabes sin poder explicar cómo lo sabes?", tags: ["sabiduría", "intuición", "realización"], difficulty: "avanzado" },
    { title: "Fé", category: "Medieval", quote: "La fe es creer sin demostración racional.", philosopher: "Agustín de Hipona", era: "400 d.C.", school: "Teología cristiana", application: "Existe un conocimiento que va más allá de la razón. No es irracionalidad, es otro modo de conocer.", prompt: "¿En qué crees sin poder probarlo?", tags: ["fe", "creencia", "trascendencia"], difficulty: "intermedio" },
    { title: "Analogía del Ser", category: "Medieval", quote: "Algo existe de muchas maneras, no de una sola.", philosopher: "Tomás de Aquino", era: "1225", school: "Escolasticismo", application: "La realidad tiene múltiples niveles de existencia. Eres más que materia.", prompt: "¿En cuántos niveles existes?", tags: ["existencia", "niveles", "ser"], difficulty: "avanzado" },
    { title: "Beatitud", category: "Medieval", quote: "La verdadera felicidad es la visión de Dios.", philosopher: "Tomás de Aquino", era: "1225", school: "Teología cristiana", application: "Independientemente de tus creencias, busca lo trascendente. Es fuente de dicha.", prompt: "¿Cuál es tu 'visión' trascendente?", tags: ["felicidad", "trascendencia", "meta"], difficulty: "intermedio" },
    { title: "Purgación", category: "Medieval", quote: "Antes de ver la verdad, debes purificarte de falsedades.", philosopher: "Dante Alighieri", era: "1321", school: "Teología medieval", application: "El camino hacia la sabiduría comienza con la purificación de creencias falsas.", prompt: "¿Qué creencia falsa necesitas soltar?", tags: ["purificación", "verdad", "liberación"], difficulty: "intermedio" },
    { title: "Humildad Socrática", category: "Clásicos", quote: "Solo sé que no sé nada.", philosopher: "Sócrates", era: "470 a.C.", school: "Platonismo", application: "La verdadera sabiduría comienza con reconocer tu ignorancia. Esto te abre al aprendizaje.", prompt: "¿Qué crees que sabes que en realidad no sabes?", tags: ["ignorancia", "aprendizaje", "humildad"], difficulty: "principiante" },
    { title: "Mayéutica Socrática", category: "Clásicos", quote: "La verdad emerge del diálogo, no de la instrucción.", philosopher: "Sócrates", era: "470 a.C.", school: "Platonismo", application: "Haz preguntas en lugar de dar respuestas. Ayuda a otros a descubrir su propia verdad.", prompt: "¿A quién podrías ayudar a través de preguntas?", tags: ["diálogo", "verdad", "enseñanza"], difficulty: "intermedio" },
    { title: "Caverna de Platón", category: "Clásicos", quote: "Los prisioneros solo ven sombras y creen que es la realidad.", philosopher: "Platón", era: "380 a.C.", school: "Platonismo", application: "La realidad que percibes puede ser ilusoria. Cuestiona constantemente tus percepciones.", prompt: "¿Qué sombras tomas por realidad?", tags: ["ilusión", "percepción", "realidad"], difficulty: "avanzado" },
    { title: "Formas de Platón", category: "Clásicos", quote: "Lo particular participa en la Forma universal.", philosopher: "Platón", era: "380 a.C.", school: "Platonismo", application: "Existe una realidad de Ideas puras detrás de las cosas materiales. Busca los principios universales.", prompt: "¿Cuál es la esencia de la cosa que amas?", tags: ["esencia", "universal", "ideal"], difficulty: "avanzado" },
    { title: "Virtud como Conocimiento", category: "Clásicos", quote: "Nadie hace el mal voluntariamente; todo mal viene de la ignorancia.", philosopher: "Sócrates", era: "470 a.C.", school: "Platonismo", application: "La virtud es conocimiento. Si conoces el bien, lo harás. La maldad es siempre ignorancia.", prompt: "¿Qué maldad en ti viene de ignorancia?", tags: ["virtud", "conocimiento", "ignorancia"], difficulty: "intermedio" },
    { title: "Prudencia", category: "Ética", quote: "La prudencia es la capacidad de discernir lo correcto en cada situación.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "La prudencia no es cautela sino sabiduría práctica. Desarrolla tu juicio.", prompt: "¿En qué situación necesitas más prudencia?", tags: ["sabiduría", "discernimiento", "práctica"], difficulty: "intermedio" },
    { title: "Templanza", category: "Ética", quote: "El equilibrio en los placeres es virtud.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Ni ascetismo extremo ni hedonismo. Busca el equilibrio en todos tus actos.", prompt: "¿Dónde careces de equilibrio?", tags: ["equilibrio", "moderación", "virtud"], difficulty: "intermedio" },
    { title: "Coraje", category: "Ética", quote: "El valor es el punto medio entre la cobardía y la temeridad.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "El coraje verdadero no es ausencia de miedo sino acción a pesar del miedo.", prompt: "¿Qué acción valiente necesitas hacer?", tags: ["coraje", "miedo", "acción"], difficulty: "intermedio" },
    { title: "Justicia Conmutativa", category: "Ética", quote: "Intercambio justo: equivalencia en las transacciones.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "La justicia requiere equivalencia. En transacciones, busca que ambos ganen.", prompt: "¿Dónde falta equivalencia en tus relaciones?", tags: ["justicia", "equidad", "intercambio"], difficulty: "intermedio" },
    { title: "Amistad Perfecta", category: "Ética", quote: "La amistad perfecta es entre iguales que se aman por su carácter.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Hay amistades de placer, utilidad y virtud. Cultiva las de virtud.", prompt: "¿Tienes amistades de virtud?", tags: ["amistad", "virtud", "relaciones"], difficulty: "intermedio" },
    { title: "Catarsis", category: "Ética", quote: "La tragedia purifica las emociones a través de la compasión y el miedo.", philosopher: "Aristóteles", era: "350 a.C.", school: "Poética", application: "Las emociones difíciles pueden purificarse. Siente completamente para liberarte.", prompt: "¿Qué emoción necesitas experimentar para purificarte?", tags: ["emoción", "purificación", "arte"], difficulty: "intermedio" },
    { title: "Actualización", category: "Metafísica", quote: "Actualizar es pasar de la potencia a la realidad.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Tienes potencial. La vida es el proceso de actualizarlo. ¿Qué potencial dejas sin realizar?", prompt: "¿Cuál es tu mayor potencial sin actualizar?", tags: ["potencial", "realización", "actualidad"], difficulty: "intermedio" },
    { title: "Ousia", category: "Metafísica", quote: "La sustancia es lo más real.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Las cosas tienen una esencia (sustancia). Las propiedades cambian pero la esencia permanece.", prompt: "¿Cuál es tu esencia que persiste a través de cambios?", tags: ["esencia", "sustancia", "identidad"], difficulty: "avanzado" },
    { title: "Causa Formal", category: "Epistemología", quote: "La forma es la causa de que algo sea lo que es.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Entender algo es conocer su forma, su principio organizador, su patrón.", prompt: "¿Cuál es la forma (patrón) de tu vida?", tags: ["forma", "patrón", "esencia"], difficulty: "avanzado" },
    { title: "Hilemorfismo", category: "Metafísica", quote: "La realidad es composición de materia y forma.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Tú no eres solo cuerpo ni solo espíritu. Eres una unidad de ambos.", prompt: "¿Cómo se relacionan tu materia (cuerpo) y tu forma (espíritu)?", tags: ["materia", "forma", "unidad"], difficulty: "avanzado" },
    { title: "Contingencia vs. Necesidad", category: "Metafísica", quote: "Lo contingente podría no ser; lo necesario debe ser.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Tu existencia es contingente, pero hay algo necesario que la fundamenta.", prompt: "¿Qué es necesario en tu vida?", tags: ["contingencia", "necesidad", "fundamento"], difficulty: "avanzado" },
    { title: "Bien Supremo", category: "Ética", quote: "El bien es aquello a lo que todas las cosas tienden.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Identifica tu bien supremo. Todo lo demás debería servir a eso.", prompt: "¿Cuál es tu bien supremo?", tags: ["bien", "propósito", "meta"], difficulty: "avanzado" },
    { title: "Contemplación", category: "Ética", quote: "La vida contemplativa es la más feliz.", philosopher: "Aristóteles", era: "350 a.C.", school: "Estagirita", application: "Más allá de la acción está la contemplación. Cultiva momentos de reflexión pura.", prompt: "¿Cuándo contemplas sin actuar?", tags: ["contemplación", "reflexión", "felicidad"], difficulty: "intermedio" },
    { title: "Logos", category: "Clásicos", quote: "El logos es la razón universal que ordena todas las cosas.", philosopher: "Heráclito", era: "500 a.C.", school: "Presocráticos", application: "Existe una razón universal en el cosmos. Tu razón es parte de ella.", prompt: "¿Sientes conexión con algo mayor que tú?", tags: ["razón", "universal", "orden"], difficulty: "avanzado" },
    { title: "Panta Rhei", category: "Clásicos", quote: "Todo fluye; nada permanece.", philosopher: "Heráclito", era: "500 a.C.", school: "Presocráticos", application: "El cambio es lo único permanente. Acepta el flujo de la vida.", prompt: "¿Con qué cambio luchas?", tags: ["cambio", "flujo", "aceptación"], difficulty: "principiante" },
    { title: "Lucha de Contrarios", category: "Clásicos", quote: "La armonía surge de la tensión de los opuestos.", philosopher: "Heráclito", era: "500 a.C.", school: "Presocráticos", application: "Conflicto y tensión son necesarios para el crecimiento. No busques la paz perfecta.", prompt: "¿Qué tensión creativa hay en tu vida?", tags: ["conflicto", "equilibrio", "armonía"], difficulty: "intermedio" },
    { title: "Ser y No-Ser", category: "Metafísica", quote: "El Ser es; el No-Ser no es.", philosopher: "Parménides", era: "450 a.C.", school: "Presocráticos", application: "Existe una realidad que es (siendo) y una que no es. Aprende a distinguir.", prompt: "¿Qué es real y qué es ilusión en tu vida?", tags: ["ser", "realidad", "ilusión"], difficulty: "avanzado" },
    { title: "Átomos", category: "Filosofía Antigua", quote: "Todo está compuesto de átomos indivisibles moviéndose en el vacío.", philosopher: "Demócrito", era: "420 a.C.", school: "Atomismo", application: "Aunque los átomos sean indivisibles, el universo es material. Materia es base.", prompt: "¿Cómo materias simples crean tu complejidad?", tags: ["materia", "composición", "física"], difficulty: "intermedio" },
    { title: "Absurdo y Libertad", category: "Existencialismo", quote: "La libertad comienza cuando aceptas el absurdo.", philosopher: "Albert Camus", era: "1942", school: "Existencialismo", application: "En un universo sin significado inherente, eres libre. Esta libertad es vertiginosa.", prompt: "¿Qué haces con tu libertad?", tags: ["libertad", "absurdo", "significado"], difficulty: "avanzado" },
    { title: "Revuelta", category: "Existencialismo", quote: "La revuelta es vivir plenamente en el absurdo.", philosopher: "Albert Camus", era: "1942", school: "Existencialismo", application: "No aceptes la injusticia pero tampoco caigas en despair. Vive en rebeldía lúcida.", prompt: "¿Contra qué te revelas?", tags: ["rebeldía", "injusticia", "resistencia"], difficulty: "avanzado" },
    { title: "Pasión por la Vida", category: "Existencialismo", quote: "A pesar del absurdo, debes elegir vivir, no morir.", philosopher: "Albert Camus", era: "1942", school: "Existencialismo", application: "La vida merece ser vivida incluso sin razón última. Ama la vida en su totalidad.", prompt: "¿Qué te hace querer seguir viviendo?", tags: ["vida", "amor", "pasión"], difficulty: "avanzado" },
    { title: "Simone Beauvoir: Segundo Sexo", category: "Feminismo", quote: "No se nace mujer, se llega a serlo.", philosopher: "Simone Beauvoir", era: "1949", school: "Existencialismo feminista", application: "El género no es esencia sino construcción social. Eres libre de redefinirte.", prompt: "¿Cuáles son tus roles sociales elegidos vs. impuestos?", tags: ["género", "identidad", "libertad"], difficulty: "avanzado" },
    { title: "Buena Fe vs. Mala Fe", category: "Existencialismo", quote: "La buena fe requiere reconocer tu libertad y responsabilidad.", philosopher: "Jean-Paul Sartre", era: "1945", school: "Existencialismo", application: "Vivir en buena fe es asumir tu responsabilidad total. Es incómodo pero auténtico.", prompt: "¿Dónde vives en mala fe?", tags: ["responsabilidad", "autenticidad", "verdad"], difficulty: "avanzado" },
    { title: "Conciencia Intencional", category: "Fenomenología", quote: "La consciencia siempre es consciencia de algo.", philosopher: "Edmund Husserl", era: "1900", school: "Fenomenología", application: "Tu consciencia apunta a objetos. Eres siempre relacionado con algo externo.", prompt: "¿De qué eres siempre consciente?", tags: ["consciencia", "intención", "relación"], difficulty: "avanzado" },
    { title: "Epojé", category: "Fenomenología", quote: "Suspende tu juicio sobre la realidad para ver su esencia.", philosopher: "Edmund Husserl", era: "1900", school: "Fenomenología", application: "Detén tus presuposiciones. Observa sin juicio. Esto revela la esencia de las cosas.", prompt: "¿Qué observarías sin tus presuposiciones actuales?", tags: ["observación", "esencia", "suspensión"], difficulty: "avanzado" },
    { title: "Mundo de la Vida", category: "Fenomenología", quote: "El mundo vivido es más fundamental que el mundo teórico.", philosopher: "Edmund Husserl", era: "1900", school: "Fenomenología", application: "Tu experiencia vivida es lo fundamental. La teoría es secundaria.", prompt: "¿Cuál es tu mundo vivido?", tags: ["experiencia", "vivencia", "realidad"], difficulty: "intermedio" },
    { title: "Ser-en-el-mundo", category: "Fenomenología", quote: "La existencia es siempre estar inmerso en un mundo.", philosopher: "Martin Heidegger", era: "1927", school: "Fenomenología", application: "No eres observador externo. Estás inmerso, implicado, comprometido con tu mundo.", prompt: "¿Cuál es tu mundo?", tags: ["existencia", "inmanencia", "mundo"], difficulty: "intermedio" },
    { title: "Estar-Ahí", category: "Fenomenología", quote: "El ser es en gran medida estar-aquí, estar-ahora.", philosopher: "Martin Heidegger", era: "1927", school: "Fenomenología", application: "Tu presencia aquí-ahora es lo más fundamental. Cultívala.", prompt: "¿Qué significa tu presencia ahora?", tags: ["presencia", "ahora", "ser"], difficulty: "intermedio" },
    { title: "Cuidado (Sorge)", category: "Fenomenología", quote: "El cuidado es la estructura fundamental del ser.", philosopher: "Martin Heidegger", era: "1927", school: "Fenomenología", application: "Tu esencia es cuidado. Importas porque cuidas y eres cuidado por otros.", prompt: "¿Por quién y qué cuidas?", tags: ["cuidado", "importancia", "relación"], difficulty: "intermedio" },
    { title: "Anticipación de la Muerte", category: "Fenomenología", quote: "Solo cuando anticipo mi muerte me vuelvo auténtico.", philosopher: "Martin Heidegger", era: "1927", school: "Fenomenología", application: "Tu mortalidad es tu autenticidad. La conciencia de que morirás te hace vivir genuinamente.", prompt: "¿Cómo cambia tu vida cuando recuerdas que morirás?", tags: ["muerte", "autenticidad", "urgencia"], difficulty: "avanzado" },
    { title: "Véase Misma", category: "Fenomenología", quote: "El mundo no es apariencia sino manifestación del ser.", philosopher: "Martin Heidegger", era: "1927", school: "Fenomenología", application: "Todo lo que ves es una manifestación del ser. Aprende a leer el mundo.", prompt: "¿Qué te manifiesta el mundo hoy?", tags: ["manifestación", "ser", "lectura"], difficulty: "avanzado" },
  ]
};

// Función para obtener conceptos por categoría
function getConceptsByCategory(category) {
  return PHILOSOPHY_DATABASE.concepts.filter(c => c.category === category);
}

// Función para obtener concepto aleatorio
function getRandomConcept() {
  return PHILOSOPHY_DATABASE.concepts[Math.floor(Math.random() * PHILOSOPHY_DATABASE.concepts.length)];
}

// Función para búsqueda
function searchConcepts(query) {
  const q = query.toLowerCase();
  return PHILOSOPHY_DATABASE.concepts.filter(c =>
    c.title.toLowerCase().includes(q) ||
    c.philosopher.toLowerCase().includes(q) ||
    c.quote.toLowerCase().includes(q) ||
    c.tags.some(tag => tag.includes(q))
  );
}

// Exportar estadísticas
function getStats() {
  return {
    totalConcepts: PHILOSOPHY_DATABASE.concepts.length,
    totalCategories: PHILOSOPHY_DATABASE.categories.length,
    categoriesWithCount: PHILOSOPHY_DATABASE.categories.map(cat => ({
      name: cat,
      count: getConceptsByCategory(cat).length
    }))
  };
}
